productly/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("",  views.inicio, name="inicio"),
    path("admin/", admin.site.urls),
    path("productos/", include("productos.urls") )
]

productos/urls.py
from django.urls import path
from . import views

app_name = 'producto'
urlpatterns = [
    path("",views.index,name="index"),
    path("<int:producto_id>", views.detalle, name="detalle"),
    path("formulario", views.formulario, name = "formulario"),
]

productos/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Categoria(models.Model):
    nombre = models.CharField(max_length=255)


    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=255)
    stock = models.IntegerField()
    puntaje = models.FloatField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    creado_en = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre

productos/forms.py
from . import models 
from django.forms import ModelForm

class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto 
        fields = ['nombre','stock','puntaje','categoria']
        

productly/views.py
from django.shortcuts import render


def inicio(request):
    return render(
        request,
        "inicio.html",
    )

productos/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from productos.forms import ProductoForm
from .models import Producto
# Create your views here.

def index(request):
    productos = Producto.objects.all()

    return render(
        request,
        "index.html",
        context={'productos':productos}
    )

def detalle(request, producto_id):
    producto = get_object_or_404(Producto, id= producto_id)
    producto = Producto.objects.get(id=producto_id)
    return render(
        request,
        "detalle.html",
        context={'producto':producto}
    )


def formulario(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productos')

    else:
        form = ProductoForm()
        
    return render(
        request,
        "producto_form.html",
        context={'form':form}
    )

productos/templates/detalle.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    <div class="card mx-auto mt-5" style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title text-center
            ">{{ producto.nombre }}</h5>
            <hr>
            <table class="table table-hover">
                <tr>
                    <td>Stock:</td>
                    <td>{{ producto.stock }}</td>
                </tr>
                <tr>
                    <td>Puntaje:</td>
                    <td>{{ producto.puntaje }}</td>
                </tr>
                <tr>
                    <td>Categoria:</td>
                    <td>{{ producto.categoria }}</td>
                </tr>
                <tr>
                    <td>Descripcion:</td>
                    <td>{{ producto.descripcion }}</td>
                </tr>
                <tr>
                    <td>Precio:</td>
                    <td>{{ producto.precio }}</td>
                </tr>
            </table>
            <div class="text-end" style="width: 28rem;">
                <a href="/productos" class="btn-sm btn-primary">Volver</a>
            </div>
            
        </div>
</div>

{% endblock %}

productos/templates/index.html
    {% extends 'base.html' %}

    {% block content %}
    
    <h1>Productos</h1>
    <a href="{% url 'producto:formulario'%}">Nuevo producto</a>

    <table class="table">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Stock</th>
                <th>Puntaje</th>
                <th>Categoria</th>
            </tr>
        </thead>
        <tbody>
            {% for producto in productos %}
            <tr>
                <td><a href="{% url 'producto:detalle' producto.id %}">

                    {{ producto.nombre}}</td>
                </a>
                <td>{{producto.stock}}</td>
                <td>{{producto.puntaje}}</td>
                <td>{{producto.categoria}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>   

    {% endblock %}

productos/templates/producto_form.html
{% extends 'base.html' %} {% block content %}
<form novalidate action="{% url 'producto:formulario' %}" method="post">
  {% csrf_token %} {{ form }}

  <input type="submit" value="Enviar" />
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'producto:index' %}">Productos</a>
              </li>
    
            </ul>
          </div>
        </div>
      </nav>

    <main class="container">
    {% block content %}

    {% endblock %}
    </main>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</html>

templates/django/forms/label.html
{% if use_tag %}
    <{{ tag }} {% include 'django/forms/attrs.html' %} class="form-label">
    {{ label }}</{{ tag }}>
{% else %}
    {{ label }}
{% endif %}

templates/django/forms/widgets/input.html
<input 
    class="form-control {{ widget.attrs.class }}"
    type="{{ widget.type }}" 
    name="{{ widget.name }}"
    {% if widget.value != None %}
        value="{{ widget.value|stringformat:'s' }}"
    {% endif %}
    {% include "django/forms/widgets/attrs.html" %}>

templates/django/forms/widgets/select.html
<select name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %} class="form-select">
    {% for group_name, group_choices, group_index in widget.optgroups %}
    {% if group_name %}
        <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
        {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
  </select>

templates/form_snippet.html
{% load add_attr %}

{% for field in form %}
    <div class="mb-3">
    {{ field.label_tag }} 
    {% if field.errors %}
        {{ field|add_attr:"class:is-invalid" }}
    {% else %}
        {{ field }}
    {% endif %}
    <div class="invalid-feedback">
    {% for error in field.errors %}
        <span style="color: red;">{{ error }}</span>
    {% endfor %}
    </div>
    </div>
 {% endfor %}           

templates/inicio.html
{% extends 'base.html' %}

{% block content %}

Hola mundo! Bienvenido a Productly! 
{% endblock  %}